#!/bin/bash
PROJECT=$(realpath "$(dirname "${0:a}")/../")
PATHS=($(realpath $PROJECT/Package.swift) $(realpath $PROJECT/Sources) $(realpath $PROJECT/Tests))
echo "Linting sources in: ${PATHS[@]}..."
swift format lint --recursive ${PATHS[@]} "$@"